/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    HeaderIcon: typeof import('./src/components/layout/components/HeaderIcon.vue')['default']
    Icon: typeof import('./src/components/icon/Icon.vue')['default']
    Layout: typeof import('./src/components/layout/Layout.vue')['default']
    MenuItem: typeof import('./src/components/layout/components/MenuItem.vue')['default']
    MenuWrapper: typeof import('./src/components/layout/components/MenuWrapper.vue')['default']
    Navbar: typeof import('./src/components/layout/Navbar.vue')['default']
    Ripple: typeof import('./src/components/ripple/Ripple.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Section: typeof import('./src/components/layout/Section.vue')['default']
    Sidebar: typeof import('./src/components/layout/Sidebar.vue')['default']
  }
}
